kind: pipeline
type: docker
name: x86_64

platform:
  os: linux
  arch: amd64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-${DRONE_STAGE_ARCH}
- name: dev
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-${DRONE_STAGE_ARCH}
- name: go
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-${DRONE_STAGE_ARCH}

---
kind: pipeline
type: docker
name: aarch64

platform:
  os: linux
  arch: arm64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-${DRONE_STAGE_ARCH}
- name: dev
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-${DRONE_STAGE_ARCH}
- name: go
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-${DRONE_STAGE_ARCH}

---
kind: pipeline
type: docker
name: ppc64le

platform:
  os: linux
  arch: ppc64le

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-${DRONE_STAGE_ARCH}
- name: dev
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-${DRONE_STAGE_ARCH}
- name: go
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-${DRONE_STAGE_ARCH}

---
kind: pipeline
type: docker
name: mips64

platform:
  os: linux
  arch: mips64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-${DRONE_STAGE_ARCH}
- name: dev
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-${DRONE_STAGE_ARCH}
- name: go
  image: abyssos/junk:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-${DRONE_STAGE_ARCH}

---
kind: pipeline
type: docker
name: manifest

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  ignore_missing: true
  platforms:
  - linux/amd64
  - linux/arm64
  - linux/mips64
  - linux/ppc64le

steps:
- name: latest
  image: plugins/manifest
  settings:
    <<: *cs
    target: abyssos/abyss:latest
    template: abyssos/abyss-archive:latest-ARCH

- name: dev
  image: plugins/manifest
  settings:
    <<: *cs
    target: abyssos/abyss:dev
    template: abyssos/abyss-archive:dev-ARCH

- name: go
  image: plugins/manifest
  settings:
    <<: *cs
    target: abyssos/abyss:go
    template: abyssos/abyss-archive:go-ARCH

depends_on:
- x86_64
- aarch64
- ppc64le
- mips64

---
kind: pipeline
type: docker
name: drone-manifest

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  ignore_missing: true
  platforms:
  - linux/amd64
  - linux/arm64
  - linux/mips64
  - linux/ppc64le

steps:
- name: drone-git
  image: plugins/manifest
  settings:
    <<: *cs
    target: abyssos/junk:drone-git
    template: abyssos/junk:drone-git-ARCH

depends_on:
- x86_64
- aarch64
- ppc64le
- mips64
