kind: pipeline
name: default

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss

steps:
- name: latest
  image: plugins/docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest
- name: dev
  image: plugins/docker
  settings:
    <<: *cs
    context: dev
    dockerfile: latest/Dockerfile
    tags: dev
