kind: pipeline
type: docker
name: x86_64

platform:
  os: linux
  arch: amd64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: plugins/docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-${DRONE_STAGE_ARCH}
- name: dev
  image: plugins/docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-${DRONE_STAGE_ARCH}

---
kind: pipeline
type: docker
name: aarch64

platform:
  os: linux
  arch: arm64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: plugins/docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-${DRONE_STAGE_ARCH}
- name: dev
  image: plugins/docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-${DRONE_STAGE_ARCH}

---
kind: pipeline
type: docker
name: manifest

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: plugins/manifest
  settings:
    <<: *cs
    target: abyssos/abyss:latest
    template: abyssos/abyss-archive:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
    ignore_missing: true

- name: dev
  image: plugins/manifest
  settings:
    <<: *cs
    target: abyssos/abyss:dev
    template: abyssos/abyss-archive:dev-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
    ignore_missing: true

depends_on:
- x86_64
- aarch64
