kind: pipeline
type: docker
name: x86_64

platform:
  os: linux
  arch: amd64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-amd64

steps:
- name: dev
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-amd64

steps:
- name: go
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-amd64

steps:
- name: drone-git
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: drone-git
    dockerfile: drone-git/Dockerfile
    tags: drone-git-amd64

steps:
- name: docker
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: docker
    dockerfile: docker/Dockerfile
    tags: docker-amd64

---
kind: pipeline
type: docker
name: aarch64

platform:
  os: linux
  arch: arm64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-arm64

steps:
- name: dev
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-arm64

steps:
- name: go
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-arm64

steps:
- name: drone-git
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: drone-git
    dockerfile: drone-git/Dockerfile
    tags: drone-git-arm64

steps:
- name: docker
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: docker
    dockerfile: docker/Dockerfile
    tags: docker-arm64

---
kind: pipeline
type: docker
name: ppc64le

platform:
  os: linux
  arch: ppc64le

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-ppc64le

steps:
- name: dev
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-ppc64le

steps:
- name: go
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-ppc64le

steps:
- name: drone-git
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: drone-git
    dockerfile: drone-git/Dockerfile
    tags: drone-git-ppc64le

steps:
- name: docker
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: docker
    dockerfile: docker/Dockerfile
    tags: docker-ppc64le

---
kind: pipeline
type: docker
name: mips64

platform:
  os: linux
  arch: mips64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss-archive

steps:
- name: latest
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest-mips64

steps:
- name: dev
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev-mips64

steps:
- name: go
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: go
    dockerfile: go/Dockerfile
    tags: go-mips64

steps:
- name: drone-git
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: drone-git
    dockerfile: drone-git/Dockerfile
    tags: drone-git-mips64

steps:
- name: docker
  image: abyssos/abyss:drone-plugins-docker
  settings:
    <<: *cs
    context: docker
    dockerfile: docker/Dockerfile
    tags: docker-mips64

---
kind: pipeline
type: docker
name: manifest

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  ignore_missing: true
  platforms:
  - linux/amd64
  - linux/arm64
  - linux/ppc64le
  - linux/mips64

steps:
- name: latest
  image: abyssos/abyss:drone-plugins-manifest
  settings:
    <<: *cs
    target: abyssos/abyss:latest
    template: abyssos/abyss-archive:latest-ARCH

steps:
- name: dev
  image: abyssos/abyss:drone-plugins-manifest
  settings:
    <<: *cs
    target: abyssos/abyss:dev
    template: abyssos/abyss-archive:dev-ARCH

steps:
- name: go
  image: abyssos/abyss:drone-plugins-manifest
  settings:
    <<: *cs
    target: abyssos/abyss:go
    template: abyssos/abyss-archive:go-ARCH

steps:
- name: drone-git
  image: abyssos/abyss:drone-plugins-manifest
  settings:
    <<: *cs
    target: abyssos/abyss:drone-git
    template: abyssos/abyss-archive:drone-git-ARCH

steps:
- name: docker
  image: abyssos/abyss:drone-plugins-manifest
  settings:
    <<: *cs
    target: abyssos/abyss:docker
    template: abyssos/abyss-archive:docker-ARCH

depends_on:
- x86_64
- aarch64
- ppc64le
- mips64
