---
kind: pipeline
name: x86_64

platform:
  os: linux
  arch: amd64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss

steps:
- name: latest
  image: plugins/docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest
- name: dev
  image: plugins/docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev

---
kind: pipeline
name: aarch64

platform:
  os: linux
  arch: arm64

common_settings: &cs
  username:
    from_secret: DOCKER_USERNAME
  password:
    from_secret: DOCKER_PASSWORD
  repo: abyssos/abyss

steps:
- name: latest
  image: plugins/docker
  settings:
    <<: *cs
    context: latest
    dockerfile: latest/Dockerfile
    tags: latest
- name: dev
  image: plugins/docker
  settings:
    <<: *cs
    context: dev
    dockerfile: dev/Dockerfile
    tags: dev
